name: ClimWIP
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - boost-cpp=1.70.0=ha2d47e9_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - cartopy=0.17.0=py37h0aa2c8f_1004
  - cdo=1.9.6=hd104f1c_1006
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37h8022711_0
  - cfitsio=3.430=h0bd2449_1002
  - cftime=1.0.3.4=py37hd352d35_1001
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cryptography=2.7=py37h72c5cf5_0
  - curl=7.64.1=hf8cf82a_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - deprecated=1.2.5=py_0
  - descartes=1.1.0=py_3
  - eccodes=2.12.3=h1ba12e4_2
  - expat=2.2.5=he1b5a44_1003
  - fftw=3.3.8=nompi_h7f3a6c3_1105
  - fiona=1.8.6=py37hf242f0b_3
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.1=py37h5f563d9_5
  - geopandas=0.5.0=py_2
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.4.3=h1105359_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=h6f030ca_1001
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1100
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_1000
  - jasper=1.900.1=h07fcdf6_1006
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.10=h58c409b_1005
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libaec=1.0.4=hf484d3e_0
  - libblas=3.8.0=7_openblas
  - libcblas=3.8.0=7_openblas
  - libcurl=7.64.1=hda55be3_0
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.4.1=h677e3de_5
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=7_openblas
  - libnetcdf=4.6.2=h056eaf5_1002
  - libpng=1.6.37=hed695b0_0
  - libpq=11.3=h4e4e079_0
  - libspatialindex=1.9.0=he1b5a44_1
  - libspatialite=4.3.0a=hb5ec416_1026
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - lz4-c=1.8.3=he1b5a44_1001
  - mapclassify=2.1.1=py_0
  - matplotlib=3.1.0=py37_1
  - matplotlib-base=3.1.0=py37hfd891ef_1
  - munch=2.3.2=py_0
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.1.2=py37h73a1b54_1
  - numpy=1.16.4=py37h95a1406_0
  - olefile=0.46=py_0
  - openblas=0.3.5=h9ac9557_1001
  - openjpeg=2.3.1=h58a6597_0
  - openssl=1.1.1b=h14c3975_1
  - ossuuid=1.6.2=hf484d3e_1000
  - owslib=0.18.0=py_0
  - pandas=0.24.2=py37hb3f55d8_0
  - pcre=8.41=hf484d3e_1003
  - pillow=6.0.0=py37he7afcd5_0
  - pip=19.1.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=h2ad7f00_6
  - poppler-data=0.4.9=1
  - postgresql=11.3=hbeee2d4_0
  - proj4=5.2.0=he1b5a44_1003
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py37_1
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py37h3010b51_1002
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.6=py37h516909a_1002
  - pyqt=5.9.2=py37hcca6a23_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h5b0a415_0
  - python-cdo=1.5.3=py_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=hf8c457e_1001
  - regionmask=0.4.0=py_0
  - requests=2.22.0=py37_0
  - rtree=0.8.3=py37h666c49c_1002
  - scikit-learn=0.21.2=py37h627018c_0
  - scipy=1.3.0=py37h921218d_0
  - setuptools=41.0.1=py37_0
  - shapely=1.6.4=py37h06cd6f9_1005
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.28.0=h8b20d00_0
  - tk=8.6.9=hed695b0_1002
  - tornado=6.0.3=py37h516909a_0
  - tzcode=2019a=h516909a_1002
  - udunits2=2.2.27.6=h4e0c4b3_1001
  - urllib3=1.24.3=py37_0
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xarray=0.12.2=py_0
  - xerces-c=3.2.2=hac72e42_1001
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.4.0=h3b9ef0a_0
